set test bz1027459

# Only run on make installcheck
if {! [installtest_p]} { untested "$test"; return }

# Use 'artifacts' dir.
set artifactsdir [setup_artifacts_dir]
set curdir [pwd]
cd $artifactsdir

exec touch trace1
spawn stap $curdir/$subdir/$test.stp
set ok 0
expect {
	-timeout 240
	-re {^hi\r\n} { incr ok; exp_continue }
	timeout { fail "$test (timeout)" }
	eof { }
}
catch {close}; catch {wait}
if {$ok == 1} then { pass "$test -p5" } else { fail "$test -p5 ($ok)" }

cd $curdir
